### PR TITLE
FM Role adjustments and Subtype support

### LINKED ISSUE #81: FM Roles not imported if CR is <1
Creatures with CRs that are fractions prevent the Role from being picked up by the regex

### LINKED ISSUE #82: Racial Subtype is not displayed on sheet
Currently if a creature has a Type and Subtype, e.g. Humanoid (Goblin), the subtype is captured in the regex in the <race> group, but this is set to `data.details.race` which is not displayed on the character sheet.

### PR DESCRIPTION
**Pull request by MaxPat931**
Closes #82 and closes #81 
Moves the `<race>` capture group to the Subtype field
Moves the Role from the Subtype field to the Source Custom field
Adds "Flee, Mortals!" to the Source Book field if Role is present

Sample: Chimeron
Old | New
image

### CODE REVIEW

**Review by jbhaywood — COMMENTED** [review]
I'm not sure how this fixes fractional CRs, since the only data pulled from this regex is from the `(?<role>\w+)` part.

I see that it's not working in a test with the "Gnoll Abyssal Archer", but the fix would have to be somewhere in the challenge parsing, with the `challenge` or `challengeDetails` regex lines I would think.

EDIT: I should add that I did test the change, but still see the "Gnoll Abyssal Archer" CR coming in as 1 instead of 1/2.

**Comment by MaxPat931** [comment]
Yea in `roleDetails`, the <role> group doesnt get captured if it's a fractional CR, that's all I should be affecting. 
Current Regex
image
PR Regex
image
Or actually it looks like we could simplify it down to this `\d+\s(?<role>\w+)`
image

It shouldnt have an impact on actually parsing the CR value though `challengeDetails` seems to capture those just fine, oddly I did not see the same thing with the Gnoll Abyssal Archer as you

Current import
image

PR Import
image
And testing this shows a new issue, the Wildcat is listed as size "Tiny or Small" causing more of an issue with my new Custom Race handling, but I doubt there are a lot of statblocks this would impact?

**Comment by jbhaywood** [comment]
I see what you're saying. That makes sense. Yeah, the regex could be reduced. Up to you. I agree that the "Tiny or Small" issue is a small edge we probably don't need to worry about unless someone else brings it up.

**Comment by MaxPat931** [comment]
fixed conflicts and went for the simpler regex

**Pull request merged**
